# Generated by 01_generate_stubs.py — do not edit by hand

from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_sym_db = _symbol_database.Default()

DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b"\n\rgreeter.proto\x12\x07greeter\" \n\x0cHelloRequest\x12\x10\n\x04name\x18\x01 \x01(\tR\x04name\"&\n\nHelloReply\x12\x18\n\x07message\x18\x01 \x01(\tR\x07message2E\n\x07Greeter\x12:\n\x08SayHello\x12\x15.greeter.HelloRequest\x1a\x13.greeter.HelloReply\"\x00\x62\x06proto3"
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "greeter_pb2", _globals)
if _descriptor._USE_C_DESCRIPTORS is False:
    DESCRIPTOR._options = None
    _globals["_HELLOREQUEST"]._serialized_start = 26
    _globals["_HELLOREQUEST"]._serialized_end = 58
    _globals["_HELLOREPLY"]._serialized_start = 60
    _globals["_HELLOREPLY"]._serialized_end = 98
    _globals["_GREETER"]._serialized_start = 100
    _globals["_GREETER"]._serialized_end = 169

HelloRequest = _globals["HelloRequest"]
HelloReply = _globals["HelloReply"]
