# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1TcVKjPB_erdcAGtUx2rsPGlkMlz9VejM
"""

print("Hello World")

"""Variables in Python"""

# x + y = 20
# 1 + 19 = 20
# 2 + 18 = 20

x = 20
print(x)
x = 50
print(x)

"""Data Types in Python"""

age = 21 #int
print(age)
print(type(age))

marks = 88.60
print(marks)
print(type(marks))

# 3 + 4i complex
c1 = 3 + 4j
print(c1)
print(type(c1))

# "hello",'adsfadf',"""adsfadfd"""
s1 = "hello my name is 'Darshan'"
s2 = 'hello my "name" is Darshan'
s3 = """my name is Darshan
welcome to 
home"""
print(s1)
print(s2)
print(s3)
print(type(s1))

# a b c 1 3 %
c = 'w'
print(c)
print(type(c))

# Boolean
ispresent = True
print(ispresent)
print(type(ispresent))

"""Sequence Data Types"""

# List
# Tuple
# Set
# Dictionary

l = [2,234,51,52,523.23423,"dfasdfas",True]
print(l)
print(type(l))

l1 = (2,234,51,52,523.23423,"dfasdfas",True)
print(l1)
print(type(l1))

s = {234,234,234,234,523,6235,325345,23,734,"adfa",False}
print(s)
print(type(s))

d = {'roll_no':21,'first_name':"Darshan",'last_name':"Khainrar",'Address':"Nashik"}
print(d)
print(type(d))

"""Rules of Variables

"""

# a to z or A to Z
# age,address,roll_no valid
# 1age,234Addres invalid
# %asldf,

age1 = 324
print(age1)

full_name = "Darshan Khairnar"

