# -*- coding: utf-8 -*-
"""Untitled8.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1e6FI1tD9EpmnLvLUjbq2CZqDEHGSWRIt

Sequential Data Types

1. String
2. List
3. Tuple
4. Set
5. Dictionary
"""

s = "this is home"
s2 = """This is my Home, 
I am from 
Nashik"""
print(s2)
print(s)
print(type(s))

l = [1,3,5,"hello",True,56.698]
print(l)
print(type(l))

t = ("Ravi",232,52,5,True,False,5.2)
print(t)
print(type(t))

t1 = 2,3,5,52,23
print(t1)
print(type(t1))

st = {4,5,5,5,5,7,234,True,"Hello"}
print(st)
print(type(st))

d = {"name":"Ravi","roll_no":25,"age":22}
print(d)
print(type(d))

