# -*- coding: utf-8 -*-
"""Untitled7.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1E7kSmZaoBeluAYtMvQ29Da6dg40soSZ2

Odd or Even
"""

n = int(input("Enter Number : "))

if n%2 == 0:
  print("Even")
else:
  print("Odd")

"""Prime Number or Composite"""

n = int(input("Enter Number : "))
f = False

for i in range(2,n):
  if n%i == 0:
    f = True
    break

if f == True:
  print("Composite")
else:
  print("Prime")

num = int(input("Enter Number : ")) #123 - 321 12%10 = 321
rev = 0

while num > 0:
  d = num%10
  rev = rev * 10 + d  
  num //= 10

print(rev)

print(121%10)

print(1%10)

print(1//10)

"""Palindrome Number"""

num = int(input("Enter Number : ")) 
rev = 0
t = num

while num > 0:
  d = num%10
  rev = rev * 10 + d  
  num //= 10

if rev == t:
  print("Palindrome Number")
else:
  print("Not Palindrome")



"""Armstrong Number"""

# 153 = 1+125+27 = 153 

n = int(input("Enter Number : "))
sum = 0
t = n

while n > 0:
  d = n%10
  sum += d**3
  n //= 10

if sum == t:
  print("Armstorng")
else:
  print("not armstrong")

# 1
# * * * * *
# * * * * *
# * * * * *
# * * * * *
# * * * * *

# 2
# *
# * *
# * * *
# * * * *


# 3
# * * * *
# * * *
# * *
# *

# 4
#       *
#     * *
#   * * *
# * * * *

5
# * * * *
#   * * *
#     * *
#       *

# 6
#       1
#     1 2 1
#   1 2 3 2 1
# 1 2 3 4 3 2 1

n = int(input("Enter Number: "))

for i in range(n):
  for j in range(n):
    print("*",end=" ")
  print()

for i in range(n):
  for j in range(i + 1):
    print("*",end=" ")
  print()

list(range(n,0,-1))

for i in range(n,0,-1):
  for j in range(i):
    print("*",end=" ")
  print()

for i in range(n):
  for k in range(n-i):
    print(" ",end=" ")
  for j in range(i + 1):
    print("*",end=" ")
  print()

